### ISSUE TITLE
Maturity +1 in display

### ISSUE THREAD

**Issue by 20dec** [dvandal/cryptonote-nodejs-pool#128]
Hi,

I set 6 but pool block show 7 to go with new block
![capture](https://user-images.githubusercontent.com/26274812/40104222-f4c28d86-5919-11e8-8bdb-879cbfe2ea09.PNG)

**Comment by dvandal** [comment]
Website files are updated to lastest ?

**Comment by 20dec** [comment]
Yes. I use lastest, you can see efficient field be removed by yourself.

**Comment by dvandal** [comment]
Fixed now. Thanks!

**Comment by 20dec** [comment]
I copy paste code in pool_block.html to my file .html
But still not yet fixed. I see you add EFFICIENCY field again but not show vaule (proof of change code already)
![capture](https://user-images.githubusercontent.com/26274812/40154016-8611217a-59b6-11e8-9399-33b8b33c6f5f.PNG)

**Comment by dvandal** [comment]
Should be fine now. Please update pool_blocks.html file with lastest code.

**Comment by 20dec** [comment]
Now it 5 to go.
![capture](https://user-images.githubusercontent.com/26274812/40154880-f3fb1610-59ba-11e8-9360-76fcbadbf664.PNG)

**Comment by 20dec** [comment]
![capture](https://user-images.githubusercontent.com/26274812/40154899-0d09fb4e-59bb-11e8-962b-79fc4ce5cc2d.PNG)

same height new block

**Comment by 20dec** [comment]
![capture](https://user-images.githubusercontent.com/26274812/40154949-624359b6-59bb-11e8-86e0-e651df070f46.PNG)

old style pool software display correct. then maybe problem in your code, not coin or config.

**Comment by dvandal** [comment]
Are you sure that pool code is up to date ?

**Comment by 20dec** [comment]
My footer is v1.3.4. i git clone it from yesterday
In daemon, when i print height, it show same as on dashboard, not +1
Coin type:
    "cnAlgorithm": "cryptonight",
    "cnVariant": 0,
    "cnBlobType": 0,

**Comment by dvandal** [comment]
I made changes today, so if you updated yesterday, just do another update ;)

**Comment by dvandal** [comment]
We are now using get_info RPC command if supported by blockchain (coin) daemon, else we fallback to getlastblockheader and I made fixes to that today.

**get_info**
Retrieve general information about the state of your node and the network.
difficulty - Network difficulty (analogous to the strength of the network)
height - Current length of longest chain known to daemon.

**Comment by 20dec** [comment]
Update lastest code. run node init.js again. And now status for new block
![capture](https://user-images.githubusercontent.com/26274812/40155768-ac999558-59bf-11e8-886b-12a53c367f55.PNG)

**Comment by 20dec** [comment]
![capture](https://user-images.githubusercontent.com/26274812/40170090-cd3d630c-59f1-11e8-8c90-862123d37c09.PNG)
other coin

**Comment by 20dec** [comment]
Please review my think:
You should make an if function
If networkheight - lastpoolblockheight = 0
-> var toGo = lastStats.config.depth - (lastStats.network.height - block.height);

If networkheigh - lastpoolblockheigh = 1
-> var toGo = lastStats.config.depth - (lastStats.network.height - block.height) + 1;

I change on my 2 pools, then it show correct. But i change manually by myself. Hope you code it auto as i show above.

**Comment by 20dec** [comment]
![screenshot_20180517-234817](https://user-images.githubusercontent.com/26274812/40191897-eff6559e-5a2c-11e8-9527-739acb607d6e.png)
![screenshot_20180517-234832](https://user-images.githubusercontent.com/26274812/40191904-f7b9612c-5a2c-11e8-802a-a9f2016cdc19.png)

**Comment by dvandal** [comment]
Should be fixed now in lastest code.
